### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by complexbrains**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
hey @complexbrains 

will merge #16 and then update this PR after that.

**Comment by Remi-Gau** [comment]
hey @complexbrains 

Not a big problem for small PRs like this but it might be better if you make your PR from a branch that has a not the name `main`. :hugs:

**Comment by complexbrains** [comment]
ughh.. yes yes! I was going to ask whether I should create a branch or not 🙈 Will do will do!

**Comment by Remi-Gau** [comment]
no worries. :-)

**Pull request merged**
