### PR TITLE
ENH: Use `GitHub` environment variables for repository API URL

### PR DESCRIPTION
**Pull request by jhlegarreta**
Use `GitHub` environment variables for repository API URL in workflow.

Documentation:
https://docs.github.com/en/actions/learn-github-actions/environment-variables

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This should allow to re-use the workflow file without modifying it across years.

**Review by Remi-Gau — APPROVED** [review]
Good call.
I definitely need to improve my github actions to be more like this.

**Comment by Remi-Gau** [comment]
> without modifying it across years

Or we could have a single website, that we reuse across years... :wink:

**Comment by jhlegarreta** [comment]
> Or we could have a single website, that we reuse across years... wink

We are not far from that: https://github.com/brainhackorg/global2021/pull/83#issuecomment-966651374

**Pull request merged**
