### PR TITLE
ENH: Add tests to issues to pages module/script

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add tests to issues to pages module and script:

Make the `scripts` module be a Python package in order to be able to
import the module.

Add testing data.

Add the necessary packages for testing in a separate requirements file.

Add the test workflow badge to the `README` file.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Cross-referencing https://github.com/brainhackorg/global2021/pull/83#issuecomment-966651374.

**Review by Remi-Gau — APPROVED** [review]
Had a quick look and it makes sense from what I can see.

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
Actually do you think you could add 2 lines in the CONTRIBUTING.md to explain where to find the code and CI related things that are in charge of the issue to page conversion.

https://github.com/brainhackorg/global2021/blob/main/CONTRIBUTING.md#projects

**Review by Remi-Gau — APPROVED** [review]
AWESOME !!!! Thanks @jhlegarreta

**Pull request merged**
